# gems
gems: [jekyll-paginate]


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               IGSN
tagline:             'Technical Documentation of the IGSN'
description:         'The IGSN is a globally unique persistent identifier for physical specimens. This site hosts the documentation of the implementation of IGSN.'
url:                 http://igsn.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              IGSN e.V.
  url:               http://www.igsn.org
  email:             info@igsn.org

# Custom vars
version:             1.1.0

